### ISSUE TITLE
Verify lat/long working on all clients

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/uReport#312] opened 2017-08-30 12:53 UTC
We've had reports (https://bloomington.in.gov/crm/tickets/view?ticket_id=160875) that the lat/long data may not be making it to the uReport system from the client. This may be specific to one of the native georeporter applications or to the open-311 proxy. At a minimum, we should confirm that this data is making it through via the web based open-311 proxy.

**Comment by markstos** [comment] 2017-09-29 21:45
I submitted  #161353 today while walking back from dropping the kids off at school. I thought I saw the app collect and submit my location, but later today my report was rejected for lack location. 

Then my  email reply to supply the address failed because the email is misconfigured to refer to a hostname that doesn't exist ("ureport-prod.bloomington.in.gov"). I'll open a separate issue about that.

**Comment by markstos** [comment] 2017-09-29 21:46
I use the Android client.

**Comment by markstos** [comment] 2017-09-29 21:46
Also, this may be a dupe of #304.

**Comment by inghamn** [comment] 2019-02-08 19:43
I think I can close out this error report.

The Android client is no longer maintained.  The web based javascript seems to working now.  Plus, we have a completely new uReport client (open311-nodejs).

**Comment by inghamn** [comment] 2019-02-08 19:47
The internal location chooser is not setting lat/long, either.

**Comment by markstos** [comment] 2019-02-08 20:11
Do you recommend that users of the Android app use the web instead?

**Comment by inghamn** [comment] 2019-02-08 20:13
Yes, we deleted if from the Play store years ago, but cannot delete from people's phones.  The new web based client should work well:

https://bloomington.in.gov/ureport

**Comment by markstos** [comment] 2019-02-08 20:54
I just used the new web version on Android and it worked great. It was about as easy to use as the Android app. :)

**Closed** 2020-03-25 19:44 UTC
